teste_full_stack/config/routes.rb
Rails.application.routes.draw do

  root 'pedidos#index', as: 'home'

  devise_for :compradors
  resources :pedidos
  resources :ingressos
  resources :compradors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

teste_full_stack/app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-social">
  <% if current_comprador %>
    <h3><%= link_to "Social Wave", home_path, :class => "title_header"%></h3>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto"></ul>

      <!-- Direcionar para se o usuário quiser cadastrar um novo ingresso -->
      <%= button_to "Criar um novo Ingresso", ingressos_path, :class => "btn mr-2 btn-outline-danger title_btn", :method => :get %>

      <!-- Editar o perfil do usuário -->
      <%= link_to 'Editar Perfil', edit_comprador_path(current_comprador.id), :class => "btn btn-outline-danger mr-2 title_btn" %>

      <!-- Parte do cadastro para logout do sistema -->
      <%= button_to "Logout", destroy_comprador_session_path, :class => "btn btn-outline-danger title_btn", :method => :delete %>
    </div>
  <% else %>
    <%= link_to "Bem-Vindo", home_path, :class=>"title_header" %>
  <% end %>
</nav>

teste_full_stack/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>TesteFullStack</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css'%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>

    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>