teste_full_stack/config/routes.rb
Rails.application.routes.draw do

  root 'pedidos#index', as: 'home'

  devise_for :compradors
  resources :pedidos
  resources :ingressos
  resources :compradors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

teste_full_stack/app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :comprador
  belongs_to :ingresso
  
end

teste_full_stack/app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: [:show, :edit, :update, :destroy]

  # GET /pedidos
  # GET /pedidos.json
  # HACK: essa parte retorna as datas acima dos dias atuais.
  def index
    @pedidos = Pedido.joins(:ingresso).where(comprador_id: current_comprador.id).where("ingressos.data > ?", Time.now)
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos
  # POST /pedidos.json
  # HACK: validação dos pedidos atuais. 
  def create
    @pedido =  Pedido.new(comprador_id: current_comprador.id, ingresso_id: params[:ingresso_id], pago: params[:pedido][:pago])
    if @pedido.ingresso.data > Time.now
      respond_to do |format|
        if @pedido.save
          format.html { redirect_to @pedido, notice: 'Pedido foi criado com sucesso.' }
          format.json { render :show, status: :created, location: @pedido }
        else
          format.html { render :new }
          format.json { render json: @pedido.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to @pedido, notice: 'Pedido não pode ser criado, porque é mais antigo que a data atual'
    end

  end

  # PATCH/PUT /pedidos/1
  # PATCH/PUT /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to @pedido, notice: 'Pedido was successfully updated.' }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido.destroy
    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: 'Pedido was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_params
      params.require(:pedido).permit(:comprador_id, :ingresso_id, :pago)
    end
end

teste_full_stack/app/helpers/pedidos_helper.rb
module PedidosHelper
end

teste_full_stack/app/views/pedidos/_form.html.erb
<div class="login">

  <%= form_with(model: pedido, local: true) do |form| %>
  <% if pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pedido.errors.count, "error") %>
        prohibited this pedido from being saved:</h2>

      <ul>
        <% pedido.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-8">
      <div class="field form-group">
        <%= form.label :ingresso_id %>
        <%= select_tag 'ingresso_id', options_from_collection_for_select(Ingresso.all, 'id', 'nome'),:class => "form-control"%>
      </div>
    </div>
    <div class="col-md-4">
      <div class="field form-check">
        <%= form.label :pago , :class => "form-check-label"%>
        <%= form.check_box :pago, id: :pedido_pago, :class => "form-check-input"%>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "Criar novo Pedido", :class => "btn btn-outline-danger title_btn"%>
  </div>
<% end %>

</div>

teste_full_stack/app/views/pedidos/edit.html.erb
<h1>Editing Pedido</h1>

<%= render 'form', pedido: @pedido %>

<%= link_to 'Mostrar', @pedido, :class => "btn btn-outline-danger title_btn" %>
<%= link_to 'Voltar', pedidos_path,  :class => "btn btn-outline-danger title_btn" %>

teste_full_stack/app/views/pedidos/index.html.erb
<% if notice %>
  <div class="alert alert-warning mt-3" role="alert">
    <%= notice %>
  </div>
<% end%>

<h2>Esses são seus pedidos
  <%= current_comprador.nome %>
</h2>

<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col" class="title_header">Nome do Ingresso</th>
      <th scope="col" class="title_header">Data</th>
      <th scope="col" class="title_header">preco</th>
      <th scope="col" class="title_header">taxa</th>
      <th scope="col" class="title_header">Pago</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @pedidos.each do |pedido| %>
      <tr>
        <td><strong><%= pedido.ingresso.nome %></strong></td>
        <td><%= pedido.ingresso.data.strftime('%d/%m/%Y') %></td>
        <td><%= pedido.ingresso.preco %></td>
        <td><%= pedido.ingresso.taxa %></td>
        <% if pedido.pago == false %>
          <td><i class="fa fa-close"></i></td>
        <% else %>
          <td><i class="fa fa-check"></i></td>
        <%end%>
        <td><%= button_to "Mostrar", pedido, :class => "btn btn-sm btn-outline-danger title_btn", :method => :get %>
        </td>
        <td><%= button_to "Editar", edit_pedido_path(pedido), :class => "btn btn-sm btn-outline-danger title_btn", :method => :get %>
        </td>
        <td><%= button_to "Cancelar", pedido, :class => "btn btn-sm btn-outline-danger title_btn", method: :delete, data: { confirm: 'Are you sure?' }%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<hr>

<div class="row">
  <div class="col-md-2">
    <%= button_to "Novo Pedido", new_pedido_path, :class => "btn btn-outline-danger title_btn", :method => :get %>
  </div>
</div>

teste_full_stack/app/views/pedidos/new.html.erb
<h1>Novo Pedido</h1>

<p id="notice"><%= notice %></p>

<%= render 'form', pedido: @pedido %>

<%= link_to 'Voltar', pedidos_path,  :class => "btn btn-outline-danger title_btn"%>

teste_full_stack/app/views/pedidos/show.html.erb
<% if notice %>
  <div class="alert alert-warning mt-3" role="alert">
    <%= notice %>
  </div>
<% end%>
  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col" class="title_header">Comprador</th>
        <th scope="col" class="title_header">Ingresso</th>
        <th scope="col" class="title_header">Pago</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @pedido.comprador.nome %></td>
        <td><%= @pedido.ingresso.nome %></td>
        <td><%= @pedido.pago %></td>
      </tr>
    </tbody>
  </table>
<%= link_to 'Editar', edit_pedido_path(@pedido), :class => "btn btn-outline-danger title_btn"%>
<%= link_to 'Voltar', pedidos_path, :class => "btn btn-outline-danger title_btn"%>