teste_full_stack/config/routes.rb
Rails.application.routes.draw do

  root 'pedidos#index', as: 'home'

  devise_for :compradors
  resources :pedidos
  resources :ingressos
  resources :compradors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

teste_full_stack/app/models/ingresso.rb
class Ingresso < ApplicationRecord
  has_one :pedido

  validates_presence_of :preco, message: 'Não pode ser deixado em branco'
  validates_presence_of :nome, message: 'Não pode ser deixado em branco'
  validates_presence_of :taxa, message: 'Não pode ser deixado em branco'
  validates_presence_of :data, message: 'Não pode ser deixado em branco'
end

teste_full_stack/app/controllers/ingressos_controller.rb
class IngressosController < ApplicationController
  before_action :set_ingresso, only: [:show, :edit, :update, :destroy]

  # GET /ingressos
  # GET /ingressos.json
  def index
    @ingressos = Ingresso.all
  end

  # GET /ingressos/1
  # GET /ingressos/1.json
  def show
  end

  # GET /ingressos/new
  def new
    @ingresso = Ingresso.new
  end

  # GET /ingressos/1/edit
  def edit
  end

  # POST /ingressos
  # POST /ingressos.json
  # TODO: achar outra solução para fazer a validação por tipo de dado, por enquanto eu ainda não vi
  # uma maneira de fazer no model a validação para tipo de dado. 
  def create
    @ingresso = Ingresso.new(ingresso_params)
    if @ingresso.preco != 0
      respond_to do |format|
        if @ingresso.save
          format.html { redirect_to @ingresso, notice: 'Ingresso was successfully created.' }
          format.json { render :show, status: :created, location: @ingresso }
        else
          format.html { render :new }
          format.json { render json: @ingresso.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to @ingresso, notice: 'Não foi criar os tipos de dados estão errados.' }
        format.json { render json: @ingresso.errors}
      end
    end
  end

  # PATCH/PUT /ingressos/1
  # PATCH/PUT /ingressos/1.json
  def update
    respond_to do |format|
      if @ingresso.update(ingresso_params)
        format.html { redirect_to @ingresso, notice: 'Ingresso was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingresso }
      else
        format.html { render :edit }
        format.json { render json: @ingresso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingressos/1
  # DELETE /ingressos/1.json
  def destroy
    @ingresso.destroy
    respond_to do |format|
      format.html { redirect_to ingressos_url, notice: 'Ingresso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingresso
      @ingresso = Ingresso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingresso_params
      params.require(:ingresso).permit(:preco, :nome, :taxa, :data)
    end
end

teste_full_stack/app/helpers/ingressos_helper.rb
module IngressosHelper
end

teste_full_stack/app/views/ingressos/_form.html.erb
<div class="login">
  <% if notice %>
    <div class="alert alert-warning mt-3" role="alert">
      <%= notice %>
    </div>
  <% end%>
  <%= form_with(model: ingresso, local: true) do |form| %>
  <% if ingresso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingresso.errors.count, "error") %>
        prohibited this ingresso from being saved:</h2>

      <ul>
        <% ingresso.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-2">
      <%= form.label :preco %>
    </div>
    <div class="col-md-8">
      <%= form.text_field :preco, id: :ingresso_preco, :class => "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <%= form.label :nome %>
    </div>
    <div class="col-md-8">
      <%= form.text_field :nome, id: :ingresso_nome, :class => "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= form.label :taxa %>
    </div>
    <div class="col-md-8">
      <%= form.text_field :taxa, id: :ingresso_taxa, :class => "form-control"%>
    </div>
  </div>

  <div class="field form-group">
    <%= form.label :data %>
    <%= form.datetime_select :data, { ampm: false }, { class: "mr-2 mt-2 form-control" } %>
  </div>

  <div class="actions">
    <%= form.submit "Enviar", :class => "btn btn-outline-danger title_btn"%>
  </div>
<% end %>
</div>

teste_full_stack/app/views/ingressos/edit.html.erb
<h1>Editar Ingresso</h1>

<%= render 'form', ingresso: @ingresso %>

<%= link_to 'Mostrar', @ingresso , :class => "btn btn-outline-danger title_btn"%>
<%= link_to 'Voltar', ingressos_path, :class => "btn btn-outline-danger title_btn" %>

teste_full_stack/app/views/ingressos/index.html.erb
<% if notice %>
  <div class="alert alert-warning mt-3" role="alert">
    <%= notice %>
  </div>
<% end%>

<h1>Ingressos</h1>

<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col" class="title_header">Preco</th>
      <th scope="col" class="title_header">Nome</th>
      <th scope="col" class="title_header">Taxa</th>
      <th scope="col" class="title_header">Data</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingressos.each do |ingresso| %>
      <tr>
        <td><%= ingresso.preco %></td>
        <td><%= ingresso.nome %></td>
        <td><%= ingresso.taxa %></td>
        <td><%= ingresso.data.strftime('%d/%m/%Y') %></td>
        <td><%= link_to 'Mostrar', ingresso, :class => "btn btn-sm btn-outline-danger title_btn" %></td>
        <td><%= link_to 'Editar', edit_ingresso_path(ingresso), :class => "btn btn-sm btn-outline-danger title_btn" %></td>
        <td><%= link_to 'Eliminar', ingresso, :class => "btn btn-sm btn-outline-danger title_btn", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Ingresso', new_ingresso_path , :class => "btn btn-outline-danger title_btn"%>

teste_full_stack/app/views/ingressos/new.html.erb
<h1>New Ingresso</h1>

<%= render 'form', ingresso: @ingresso %>

<%= link_to 'Voltar', ingressos_path,  :class => "btn btn-outline-danger title_btn" %>

teste_full_stack/app/views/ingressos/show.html.erb
<% if notice %>
  <div class="alert alert-warning mt-3" role="alert">
    <%= notice %>
  </div>
<% end%>
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col" class="title_header">Preço</th>
      <th scope="col" class="title_header">Nome</th>
      <th scope="col" class="title_header">Taxa</th>
      <th scope="col" class="title_header">Data</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @ingresso.preco %></td>
      <td><%= @ingresso.nome %></td>
      <td><%= @ingresso.taxa %></td>
      <td><%= @ingresso.data.strftime('%d/%m/%Y') %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Editar', edit_ingresso_path(@ingresso), :class => "btn btn-outline-danger title_btn" %>
<%= link_to 'Voltar', ingressos_path, :class => "btn btn-outline-danger title_btn" %>