teste_full_stack/config/routes.rb
Rails.application.routes.draw do

  root 'pedidos#index', as: 'home'

  devise_for :compradors
  resources :pedidos
  resources :ingressos
  resources :compradors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

teste_full_stack/app/models/comprador.rb
class Comprador < ApplicationRecord
  has_one :pedido
  validates :nome, presence: true, length: { maximum: 50 }

  validates_presence_of :telefone, message: 'Não pode ser deixado em branco'
  validates_presence_of :email, message: 'Não pode ser deixado em branco'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

teste_full_stack/app/controllers/compradors_controller.rb
class CompradorsController < ApplicationController
  before_action :set_comprador, only: [:show, :edit, :update, :destroy]

  # GET /compradors
  # GET /compradors.json
  def index
    @compradors = Comprador.all
  end

  # GET /compradors/1
  # GET /compradors/1.json
  def show
  end

  # GET /compradors/new
  def new
    @comprador = Comprador.new
  end

  # GET /compradors/1/edit
  def edit
  end

  # POST /compradors
  # POST /compradors.json
  def create
    @comprador = Comprador.new(comprador_params)

    respond_to do |format|
      if @comprador.save
        format.html { redirect_to home_path, notice: 'Comprador foi criado.' }
        format.json { render :show, status: :created, location: @comprador }
      else
        format.html { render :new }
        format.json { render json: @comprador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compradors/1
  # PATCH/PUT /compradors/1.json
  def update
    respond_to do |format|
      if @comprador.update(comprador_params)
        format.html { redirect_to @comprador, notice: 'Comprador foi atualizado.' }
        format.json { render :show, status: :ok, location: @comprador }
      else
        format.html { render :edit }
        format.json { render json: @comprador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compradors/1
  # DELETE /compradors/1.json
  def destroy
    @comprador.destroy
    respond_to do |format|
      format.html { redirect_to compradors_url, notice: 'Ok, foi eliminado comprador.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comprador
      @comprador = Comprador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comprador_params
      params.require(:comprador).permit(:nome, :telefone, :admin)
    end
end

teste_full_stack/app/helpers/compradors_helper.rb
module CompradorsHelper
end

teste_full_stack/app/views/compradors/_form.html.erb
<div class="login">
  <%= form_with(model: comprador, local: true) do |form| %>
  <% if comprador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comprador.errors.count, "error") %>
        prohibited this comprador from being saved:</h2>

      <ul>
        <% comprador.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-2">
      <%= form.label :telefone %>
    </div>
    <div class="col-md-8">
      <%= form.text_field :telefone, id: :comprador_telefone , :class => "form-control"%>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= form.label :nome %>
    </div>
    <div class="col-md-8">
      <%= form.text_field :nome, id: :comprador_nome , :class => "form-control"%>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= form.label :admin %>
    </div>
    <div class="col-md-8">
      <%= form.check_box :admin, id: :comprador_admin , :class => "form-check"%>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= form.label :email %>
    </div>
    <div class="col-md-8">
      <%= form.text_field :email, id: :comprador_admin , :class => "form-control"%>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "Enviar", :class => "btn btn-outline-danger title_btn"%>
  </div>
<% end %>
</div>

teste_full_stack/app/views/compradors/edit.html.erb
<h1>Editar Comprador</h1>

<%= render 'form', comprador: @comprador %>

<%= link_to 'Mostrar', @comprador , :class => "btn btn-outline-danger title_btn"%>
<%= link_to 'Voltar', home_path , :class => "btn btn-outline-danger title_btn"%>

teste_full_stack/app/views/compradors/index.html.erb
<% if notice %>
  <div class="alert alert-warning mt-3" role="alert">
    <%= notice %>
  </div>
<% end%>

<h1>Compradores</h1>

<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col" class="title_header">Nome</th>
      <th scope="col" class="title_header">Telefone</th>
      <th scope="col" class="title_header">Admin</th>
      <th scope="col" class="title_header">Email</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @compradors.each do |comprador| %>
      <tr>
        <td><%= comprador.nome %></td>
        <td><%= comprador.telefone %></td>
        <td><%= comprador.admin %></td>
        <td><%= comprador.email %></td>
        <td><%= link_to 'Mostar', comprador, :class => "btn btn-sm btn-outline-danger title_btn" %></td>
        <td><%= link_to 'Editar', edit_comprador_path(comprador), :class => "btn btn-sm btn-outline-danger title_btn" %></td>
        <td><%= link_to 'Eliminar', comprador, :class => "btn btn-sm btn-outline-danger title_btn", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to('Logout', destroy_comprador_session_path, :class => "btn btn-sm btn-outline-danger title_btn", :method=>'delete') %>
<%= link_to 'Novo Comprador', new_comprador_path , :class => "btn btn-sm btn-outline-danger title_btn"%>

teste_full_stack/app/views/compradors/new.html.erb
<h1>New Comprador</h1>
<% if notice %>
  <div class="alert alert-warning mt-3" role="alert">
    <%= notice %>
  </div>
<% end%>

<%= render 'form', comprador: @comprador %>

<%= link_to 'Voltar', home_path , :class => "btn btn-outline-danger title_btn" %>

teste_full_stack/app/views/compradors/show.html.erb
<% if notice %>
  <div class="alert alert-warning mt-3" role="alert">
    <%= notice %>
  </div>
<% end%>
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col" class="title_header">Nome</th>
      <th scope="col" class="title_header">Telefone</th>
      <th scope="col" class="title_header">Admin</th>
      <th scope="col" class="title_header">email</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @comprador.nome %></td>
      <td><%= @comprador.telefone %></td>
      <td><%= @comprador.admin %></td>
      <td><%= @comprador.email %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Editar', edit_comprador_path(@comprador), :class => "btn btn-outline-danger title_btn" %>
<%= link_to 'Voltar', compradors_path , :class => "btn btn-outline-danger title_btn" %>